FROM debian

RUN apt-get update && \
    apt-get install sudo && \
    apt-get install wget && \
    sudo apt-get install bzip2

EXPOSE 10011
#BUILD: docker build ./ -t ex01
#RUN: docker run -it ex01
# root@e56abb84f854:/opt/teamspeak3-server# ./ts3server_minimal_runscript.sh
# https://terminal28.com/how-to-install-and-configure-teamspeak3-server-linux-debian-ubuntu/